name: Build Tags
on:
  push:
    tags:
      - "*"
permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for goreleaser/goreleaser-action to create a GitHub release
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download dependencies
        run:  go mod download

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
